ekf_filter_node:
  ros__parameters:
    frequency: 30.0  # Hz
    two_d_mode: true  # ใช้เฉพาะ 2D
    publish_tf: true
    publish_acceleration: false

    # Frame Definitions
    map_frame: "map"               
    odom_frame: "odom"              
    base_link_frame: "base_footprint"  
    world_frame: "odom"

    # Sensor Fusion Configuration
    odom0: "/odom"
    odom0_config: [true, true, false,  # x, y, z
                   false, false, true,  # roll, pitch, yaw
                   true, true, false,   # vx, vy, vz
                   false, false, true,  # vroll, vpitch, vyaw
                   false, false, false] # ax, ay, az

    imu0: "/imu_data/data"
    imu0_config: [false, false, false,  
                  true, true, true,    
                  false, false, false,  
                  false, false, true,  
                  true, true, true]    

    pose0: "/aruco_marker_pose_base"
    pose0_config: [true, true, false, 
                   false, false, true,  
                   false, false, false,  
                   false, false, false,  
                   false, false, false]

    # Covariance (ปรับตามเซ็นเซอร์)
    odom0_differential: false
    imu0_differential: true
    pose0_differential: false

    # Process Noise
    process_noise_covariance: [0.05, 0.05, 0.01, 0.01, 0.01, 0.1]

    # IMU Yaw Offset
    imu0_remove_gravitational_acceleration: true
